name: Publish
on:
  push:
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      - name: guarded action
        run: 'echo "performing action"' 
        if: github.ref == 'refs/heads/master' || startsWith(github.ref,'refs/heads/release/')

